name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  overcommit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Prepare environment
        run: |
          git config --global user.email "gh-actions@example.com"
          git config --global user.name "GitHub Actions"
          bundle exec overcommit --sign
          bundle exec overcommit --sign pre-commit

      - name: Run pre-commit checks
        run: bundle exec overcommit --run
